### ISSUE TITLE
Crush on run

### ISSUE THREAD

**Issue by kirsan31** [yarseyah/sentinel#1] opened 2018-02-19 09:15 UTC
Hi. When I run latest version, it's crushes with this exception (Win7 x64):

> Application: Sentinel.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.NullReferenceException
>    at MS.Internal.FontCache.FontFaceLayoutInfo+IntMap.TryGetValue(Int32, UInt16 ByRef)
>    at System.Windows.Media.GlyphTypeface.Initialize(System.Uri, System.Windows.Media.StyleSimulations)
>    at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(System.Xaml.XamlType, System.Object, Boolean)
>    at System.Xaml.XamlObjectWriter.Logic_EndInit(MS.Internal.Xaml.Context.ObjectWriterContext)
>    at System.Xaml.XamlObjectWriter.WriteEndObject()
>    at System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter, Boolean, Boolean, Boolean, System.Xaml.IXamlLineInfo, System.Xaml.IXamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack`1<System.Windows.Markup.WpfXamlFrame>, System.Windows.Markup.IStyleConnector)
>    at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
>    at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
>    at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
>    at Sentinel.Controls.MainWindow..ctor()
> 
> Exception Info: System.Reflection.TargetInvocationException
>    at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
>    at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
>    at System.Activator.CreateInstance(System.Type, Boolean)
>    at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef)
>    at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
>    at System.Activator.CreateInstance(System.Type, System.Object[])
>    at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(System.Type, System.Object[])
>    at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(System.Object[])
>    at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(System.Xaml.XamlType, System.Object[])
>    at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(MS.Internal.Xaml.Context.ObjectWriterContext)
>    at System.Xaml.XamlObjectWriter.WriteStartMember(System.Xaml.XamlMember)
>    at System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter, Boolean, Boolean, Boolean, System.Xaml.IXamlLineInfo, System.Xaml.IXamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack`1<System.Windows.Markup.WpfXamlFrame>, System.Windows.Markup.IStyleConnector)
>    at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
>    at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
>    at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
>    at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
>    at System.Windows.Application.DoStartup()
>    at System.Windows.Application.<.ctor>b__1_0(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Application.RunDispatcher(System.Object)
>    at System.Windows.Application.RunInternal(System.Windows.Window)
>    at Sentinel.MainApplication.Main()
> 
>

**Comment by yarseyah** [comment] 2018-02-24 12:58
Hi, is it just the most recent release? (e.g. does the previous one work?)

That stack is deep within WPF so some questions about your GUI might be in order.  Are you using Windows in classic-desktop mode (e.g. non-Aero type interface) or have you removed any standard fonts?

Regards,
Ray

**Comment by kirsan31** [comment] 2018-02-24 13:26
It's only version I tried. Hm, about fonts... I tweaked them to remove native fonts smoothing (Clear type) on win 7... As I remebwer, I used this tool: 
https://www.sevenforums.com/customization/77125-windows-aero-tahoma-font.html

**Comment by yarseyah** [comment] 2018-02-24 14:13
Seems related to that.  I've replicated the crash on a virtual machine of Win 7 (x86) that I got from modern.ie.  Before following those instructions it worked fine, afterwards it crashed.

Restoring the font (using the Windows 7 version of "NoSegoe - Restore Segoe UI.reg") reverted it to run again.  I suspect only removing the font was the root cause.

I will see whether I can define a fallback font.

**Comment by yarseyah** [comment] 2018-02-24 15:39
Fixed in [0.13.2.0](https://github.com/yarseyah/sentinel/releases/tag/0.13.2.0)

**Closed by yarseyah** 2018-02-24 15:39 UTC

**Comment by kirsan31** [comment] 2018-02-24 15:42
Yea, all ok now - thanks.
